services:
  taser-ros-jazzy:
    image: khaledjalloul/taser:ros-jazzy
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros-jazzy
    container_name: taser-ros-jazzy
    hostname: &hostname taser
    devices: &devices
      - /dev/dri:/dev/dri
    environment: &environment
      - DISPLAY=${DISPLAY}
    volumes: &volumes
      # Enable GUI
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ../src
        target: /home/taser/colcon_ws/src
      - type: bind
        source: ../outputs
        target: /home/taser/colcon_ws/outputs
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "source ~/colcon_ws/install/setup.bash && \
        ros2 launch state_machine state_machine.launch.yaml"

  taser-isaaclab:
    image: khaledjalloul/taser:isaaclab
    build:
      context: ..
      dockerfile: docker/Dockerfile.isaaclab
      target: isaaclab
    container_name: taser-isaaclab
    hostname: *hostname
    devices: *devices
    environment: *environment
    volumes:
      - <<: *volumes
      - type: volume
        source: taser-omni-cache
        target: /home/taser/.local/lib/python3.10/site-packages/omni/cache

  taser-isaaclab-ros-humble:
    image: khaledjalloul/taser:isaaclab-ros-humble
    build:
      context: ..
      dockerfile: docker/Dockerfile.isaaclab
      target: isaaclab-ros-humble
    container_name: taser-isaaclab-ros-humble
    hostname: *hostname
    devices: *devices
    environment: *environment
    volumes:
      - <<: *volumes
      - type: volume
        source: taser-omni-cache
        target: /home/taser/.local/lib/python3.10/site-packages/omni/cache
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "source ~/colcon_ws/install/setup.bash && \
        source ~/venv/bin/activate && \
        python src/taser_isaaclab/taser_isaaclab/tasks/balance/sim.py"

volumes:
  taser-omni-cache:
    name: taser-omni-cache
    external: true
