services:
  taser:
    image: khaledjalloul/taser:${ISAACSIM_VERSION}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USERNAME: ${DOCKER_USERNAME}
        ISAACSIM_VERSION: ${ISAACSIM_VERSION}
      network: host # Temporary fix for when using VPN
    container_name: taser
    hostname: taser
    network_mode: host # Temporary fix for when using VPN
    environment:
      - DISPLAY=${DISPLAY}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMNI_KIT_ALLOW_ROOT=1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    entrypoint: bash docker/entrypoint.bash
    command: bash -c "while sleep 1000; do :; done"
    volumes:
      # Bind source code
      - type: bind
        source: ..
        target: /workspace/taser
      # Enable GUI
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      # Xauthority for X11 forwarding
      - type: bind
        source: ${HOME}/.Xauthority
        target: ${DOCKER_HOME}/.Xauthority
        read_only: false
      # Isaac Sim kit cache
      - type: bind
        source: ${HOME}/docker/taser/cache/kit
        target: /isaac-sim/kit/cache
      # OV cache
      - type: bind
        source: ${HOME}/docker/taser/cache/ov
        target: ${DOCKER_HOME}/.cache/ov
      # pip cache
      - type: bind
        source: ${HOME}/docker/taser/cache/pip
        target: ${DOCKER_HOME}/.cache/pip
      # NVIDIA GLCache
      - type: bind
        source: ${HOME}/docker/taser/cache/glcache
        target: ${DOCKER_HOME}/.cache/nvidia/GLCache
      # NVIDIA ComputeCache
      - type: bind
        source: ${HOME}/docker/taser/cache/computecache
        target: ${DOCKER_HOME}/.nv/ComputeCache
      # Omniverse logs
      - type: bind
        source: ${HOME}/docker/taser/logs
        target: ${DOCKER_HOME}/.nvidia-omniverse/logs
      # Omniverse data
      - type: bind
        source: ${HOME}/docker/taser/data
        target: ${DOCKER_HOME}/.local/share/ov/data
      # Documents
      - type: bind
        source: ${HOME}/docker/taser/documents
        target: ${DOCKER_HOME}/Documents
