services:
  taser-ros-jazzy:
    image: khaledjalloul/taser:ros-jazzy
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros-jazzy
    container_name: taser-ros-jazzy
    hostname: &hostname taser
    devices: &devices
      - /dev/dri:/dev/dri
    environment: &environment
      - DISPLAY=${DISPLAY}
    env_file: &env_file
      - ../.env.local
    volumes: &volumes
      - /tmp/.X11-unix:/tmp/.X11-unix # Enable GUI
      - ../src:/home/taser/colcon_ws/src
      - ../outputs:/home/taser/colcon_ws/outputs
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "source ~/colcon_ws/install/setup.bash && \
        ros2 launch state_machine state_machine.launch.yaml"

  taser-isaaclab:
    image: khaledjalloul/taser:isaaclab
    build:
      context: ..
      dockerfile: docker/Dockerfile.isaaclab
      target: isaaclab
    container_name: taser-isaaclab
    hostname: *hostname
    devices: *devices
    environment: *environment
    env_file: *env_file
    volumes: *volumes

  taser-isaaclab-ros-humble:
    image: khaledjalloul/taser:isaaclab-ros-humble
    build:
      context: ..
      dockerfile: docker/Dockerfile.isaaclab
      target: isaaclab-ros-humble
    container_name: taser-isaaclab-ros-humble
    hostname: *hostname
    devices: *devices
    environment: *environment
    env_file: *env_file
    volumes: *volumes
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "source ~/colcon_ws/install/setup.bash && \
        source ~/venv/bin/activate && \
        python src/taser_isaaclab/taser_isaaclab/rl/train.py --num_envs 128 --headless"
