FROM nvcr.io/nvidia/isaac-lab:2.2.0

###############################################
# Initial Setup

# Set required environment variables and shell
ENV PLATFORM=amd64
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]

# Install apt packages
RUN apt update
RUN apt install -y \
    # Essentials
    sudo \
    curl \
    bash-completion \
    # Cmake
    build-essential \
    cmake \
    # C++
    gdb \
    # Git
    git \
    git-lfs \
    # C++ dependencies
    libboost-all-dev \
    libeigen3-dev \
    libgtest-dev

# Enable bash completion
RUN echo ". /etc/bash_completion" >> ${HOME}/.bashrc

###############################################
# Isaac Sim

# Create Isaac Sim workspace folder
RUN ln -s /isaac-sim /workspace/isaacsim

# Create aliases for omni_python and isaacsim
RUN printf ' \
    \ralias omni_python="/workspace/isaacsim/python.sh" \n \
    \ralias isaacsim="/workspace/isaacsim/isaac-sim.sh" \n \
    ' >> ${HOME}/.bashrc

# Enable Isaac Sim internal rclpy library 
ENV ROS_DISTRO=humble
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/isaac-sim/exts/isaacsim.ros2.bridge/humble/lib

###############################################
# Install Dependencies

# Install Osqp and OsqpEigen
WORKDIR /tmp
RUN git clone --recursive --branch v0.6.3 https://github.com/osqp/osqp
RUN mkdir -p osqp/build
RUN cd osqp/build && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
RUN cd osqp/build && make && make install

RUN git clone --branch v0.8.1 https://github.com/robotology/osqp-eigen.git
RUN mkdir -p osqp-eigen/build
RUN cd osqp-eigen/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
RUN cd osqp-eigen/build && make && make install
ENV OsqpEigen_DIR=/usr

# Install pybind11
RUN /workspace/isaacsim/python.sh -m pip install pybind11

# Install personal CLI
RUN echo "deb [trusted=yes] https://khaledjalloul.github.io/debian-repository unstable main" | tee /etc/apt/sources.list.d/khaledjalloul.list
RUN apt update
RUN apt install -y khaled-cli

###############################################
# Finalization

ENV WORKSPACE=/workspace/taser
WORKDIR ${WORKSPACE}

# Install project
COPY ./pyproject.toml ${WORKSPACE}
COPY ./src/taser_cpp ${WORKSPACE}/src/taser_cpp
RUN mkdir -p ${WORKSPACE}/src/taser
RUN PYBIND11_DIR=$(/workspace/isaacsim/python.sh -c "import pybind11; print(pybind11.get_cmake_dir())") \
    /workspace/isaacsim/python.sh -m pip install --verbose -e .

# Update environment variables for the Python bindings
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/isaac-sim/kit/python/lib/python3.11/site-packages/lib

ENTRYPOINT [ ]