services:
  taser:
    image: khaledjalloul/taser
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: ${USERNAME} # Set as empty string to use root
        BASE_IMAGE: nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04
        ROS_DISTRO: jazzy # Ubuntu 24.04 -> jazzy, Ubuntu 22.04 -> humble
    container_name: taser
    hostname: taser
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMNI_KIT_ACCEPT_EULA=YES # Isaac Sim Requirement
      - OMNI_KIT_ALLOW_ROOT=1 # In case the user was root
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: bash -c "while sleep 1000; do :; done"
    volumes:
      # Bind source code
      - type: bind
        source: ..
        target: /workspaces/taser_ws
      # Enable GUI
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      # Persist Isaac Sim cache
      - type: volume
        source: ov-cache
        target: ${HOME}/.cache/ov # Set to /root if necessary
      - type: volume
        source: isaacsim-kit-cache
        target: /workspaces/isaacsim/kit/cache

volumes:
  ov-cache:
    # Override default compose volume name
    name: ov-cache
  isaacsim-kit-cache:
    name: isaacsim-kit-cache
